# Asana kanban workflow — board sections drive the lifecycle.
#
# Section flow: Todo → Planned → Doing → In Review → Done
#
# 1. Tag a task "erg" while it sits in the Todo section
# 2. Claude analyzes the issue, explores the codebase, and posts a plan as a comment
# 3. Card moves to "Planned" — human reads and optionally gives feedback
# 4. Any comment that isn't an approval → Claude revises and re-posts the plan
# 5. Approval comment ("LGTM", "go", etc.) OR 24h of silence → wait for card to move
# 6. Drag the card to "Doing" — Claude picks up and codes the solution
# 7. PR opened → card moves to "In Review" while CI runs
# 8. CI passes → reviewer assigned → PR approved → merged → card moves to "Done"

workflow: asana-kanban
start: planning

source:
  provider: asana
  filter:
    project: "1213476871486785"
    section: To do

states:
  # ── Planning phase (card in Todo) ───────────────────────────────

  planning:
    type: task
    action: ai.plan
    params:
      max_turns: 30
      max_duration: 15m
    next: move_to_planned
    error: notify_failed

  # Move card to "Planned" to signal the plan is ready for review
  move_to_planned:
    type: task
    action: asana.move_to_section
    params:
      section: Planned
    next: await_plan_feedback
    error: await_plan_feedback

  # Wait for human feedback on the plan.
  # - Non-approval comments trigger re-planning.
  # - Approval phrases advance to await_doing.
  # - After 24h with no comments, silently move on to wait for "Doing".
  await_plan_feedback:
    type: wait
    event: plan.user_replied
    params:
      approval_pattern: "(?i)(LGTM|looks good|approved?|proceed|go ahead|ship it)"
    timeout: 24h
    timeout_next: await_doing
    next: check_plan_feedback
    error: notify_failed

  check_plan_feedback:
    type: choice
    choices:
      - variable: plan_approved
        equals: true
        next: await_doing
      - variable: plan_approved
        equals: false
        next: planning
    default: planning

  # ── Waiting for card to move to "Doing" ─────────────────────────

  # Gate on a human dragging the card to "Doing" on the board.
  # This is the signal that the plan is accepted and work should begin.
  await_doing:
    type: wait
    event: asana.in_section
    params:
      section: Doing
    timeout: 7d
    timeout_next: plan_expired
    next: coding
    error: notify_failed

  # ── Coding phase ─────────────────────────────────────────────────

  coding:
    type: task
    action: ai.code
    params:
      max_turns: 50
      max_duration: 30m
    next: open_pr
    error: notify_failed

  open_pr:
    type: task
    action: github.create_pr
    params:
      link_issue: true
    next: move_to_in_review
    error: notify_failed

  # Move card to "In Review" while CI runs and reviewer looks at the PR
  move_to_in_review:
    type: task
    action: asana.move_to_section
    params:
      section: In Review
    next: await_ci
    error: await_ci

  # ── CI phase ─────────────────────────────────────────────────────

  await_ci:
    type: wait
    event: ci.complete
    timeout: 2h
    timeout_next: ci_timed_out
    params:
      on_failure: fix
    next: check_ci
    error: notify_failed

  check_ci:
    type: choice
    choices:
      - variable: conflicting
        equals: true
        next: rebase
      - variable: ci_passed
        equals: true
        next: request_reviewer
      - variable: ci_failed
        equals: true
        next: fix_ci
    default: notify_failed

  rebase:
    type: task
    action: git.rebase
    params:
      max_rebase_rounds: 3
    next: await_ci
    error: resolve_conflicts

  resolve_conflicts:
    type: task
    action: ai.resolve_conflicts
    params:
      max_conflict_rounds: 3
    next: push_conflict_fix
    error: notify_failed

  push_conflict_fix:
    type: task
    action: github.push
    next: await_ci
    error: notify_failed

  fix_ci:
    type: task
    action: ai.fix_ci
    params:
      max_ci_fix_rounds: 3
    next: push_ci_fix
    error: ci_unfixable

  push_ci_fix:
    type: task
    action: github.push
    next: await_ci
    error: notify_failed

  ci_unfixable:
    type: task
    action: github.comment_pr
    params:
      body: "CI fix attempts exhausted after 3 rounds. Manual intervention required."
    next: notify_failed
    error: notify_failed

  ci_timed_out:
    type: task
    action: github.comment_pr
    params:
      body: "CI has been running for over 2h. Please check the CI pipeline."
    next: notify_failed
    error: notify_failed

  # ── Review phase ─────────────────────────────────────────────────

  request_reviewer:
    type: task
    action: github.request_review
    params:
      reviewer: zhubert
    next: await_review
    error: await_review

  await_review:
    type: wait
    event: pr.reviewed
    timeout: 48h
    timeout_next: review_overdue
    params:
      auto_address: true
      max_feedback_rounds: 3
    next: merge
    error: notify_failed

  review_overdue:
    type: task
    action: github.comment_pr
    params:
      body: "This PR has been awaiting review for 48h. Could a maintainer take a look?"
    next: notify_failed
    error: notify_failed

  # ── Merge and close ──────────────────────────────────────────────

  merge:
    type: task
    action: github.merge
    params:
      method: rebase
      cleanup: true
    next: move_to_done
    error: notify_failed

  move_to_done:
    type: task
    action: asana.move_to_section
    params:
      section: Done
    next: done
    error: done

  # ── Terminal states ──────────────────────────────────────────────

  plan_expired:
    type: task
    action: asana.comment
    params:
      body: "The plan has been waiting 7 days for the card to move to 'Doing'. Move the card when ready to proceed, or remove the 'erg' tag to cancel."
    next: failed
    error: failed

  notify_failed:
    type: task
    action: asana.comment
    params:
      body: "Unable to complete automatically. Manual intervention required."
    next: failed
    error: failed

  done:
    type: succeed

  failed:
    type: fail
